In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
data = pd.read_csv('data/onlinefoods.csv', engine='pyarrow')

In [4]:
data.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes

In [5]:
data.shape

(388, 13)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         388 non-null    int64
 1   Gender                      388 non-null    object
 2   Marital Status              388 non-null    object
 3   Occupation                  388 non-null    object
 4   Monthly Income              388 non-null    object
 5   Educational Qualifications  388 non-null    object
 6   Family size                 388 non-null    int64
 7   latitude                    388 non-null    float64
 8   longitude                   388 non-null    float64
 9   Pin code                    388 non-null    int64
 10  Output                      388 non-null    object
 11  Feedback                    388 non-null    object
 12                              388 non-null    object
dtypes: float64(2), int64(3), object(8)
memory usage: 39.5+ KB

# Deleting redundant columns

In [7]:
data.head(1)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes

In [8]:
data.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'latitude', 'longitude',
       'Pin code', 'Output', 'Feedback', ''],
      dtype='object')

In [9]:
columns_to_keep = ['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income', 'Educational Qualifications', 'Family size', 'Output', 'Feedback']
columns_to_drop = ['latitude', 'longitude', 'Pin code', '']

In [10]:
numbers_columns = len(columns_to_keep) + len(columns_to_drop)

In [11]:
print(data.shape[1] == numbers_columns)

True

## 1st Method, filtering the columns that we wanted

In [12]:
modify_data = data[columns_to_keep]

In [13]:
modify_data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Yes,Positive
...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,Yes,Positive
384,23,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
385,22,Female,Single,Student,No Income,Post Graduate,5,Yes,Positive
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Yes,Positive
387,23,Male,Single,Student,No Income,Post Graduate,5,Yes,Positive

# 2nd way, dropping the unnecessary columns

In [14]:
data.drop(columns=columns_to_drop, inplace=True)

In [15]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Yes,Positive
...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,Yes,Positive
384,23,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
385,22,Female,Single,Student,No Income,Post Graduate,5,Yes,Positive
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Yes,Positive
387,23,Male,Single,Student,No Income,Post Graduate,5,Yes,Positive

# Renaming the columns

In [16]:
data.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'Output', 'Feedback'],
      dtype='object')

In [17]:
data.rename(columns={'Monthly Income': 'Monthly Salary'}, inplace=True)

In [18]:
data

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Yes,Positive
...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,Yes,Positive
384,23,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
385,22,Female,Single,Student,No Income,Post Graduate,5,Yes,Positive
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Yes,Positive
387,23,Male,Single,Student,No Income,Post Graduate,5,Yes,Positive

# Dropping duplicates

In [19]:
data.duplicated().value_counts()

False    244
True     144
Name: count, dtype: int64

In [20]:
data.drop_duplicates(inplace=True)

In [21]:
data.duplicated().sum()

np.int64(0)

# Remove the NaN values from dataset

In [22]:
data.isna().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Salary                0
Educational Qualifications    0
Family size                   0
Output                        0
Feedback                      0
dtype: int64

In [23]:
data.dropna(inplace=True)

In [24]:
data.isna().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Salary                0
Educational Qualifications    0
Family size                   0
Output                        0
Feedback                      0
dtype: int64

# Check for some more Transformations

In [25]:
data['Age (Monthd)'] = data['Age'] * 12

In [26]:
data.head(3)

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Output,Feedback,Age (Monthd)
0,20,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive,240
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Yes,Positive,288
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Yes,Negative,264

In [27]:
data['Gender'] = data['Gender'].apply(lambda x: 1 if x == 'Female' else 0)

In [28]:
data['Family size'] = data['Family size'].apply(lambda x: 'large' if x > 3 else 'small')

In [29]:
data

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Output,Feedback,Age (Monthd)
0,20,1,Single,Student,No Income,Post Graduate,large,Yes,Positive,240
1,24,1,Single,Student,Below Rs.10000,Graduate,small,Yes,Positive,288
2,22,0,Single,Student,Below Rs.10000,Post Graduate,small,Yes,Negative,264
3,22,1,Single,Student,No Income,Graduate,large,Yes,Positive,264
4,22,0,Single,Student,Below Rs.10000,Post Graduate,large,Yes,Positive,264
...,...,...,...,...,...,...,...,...,...,...
355,21,0,Single,Student,No Income,Graduate,small,No,Positive,252
363,31,0,Married,Employee,More than 50000,Ph.D,small,Yes,Positive,372
369,30,0,Married,Employee,More than 50000,Post Graduate,large,Yes,Positive,360
374,21,0,Single,Student,No Income,Graduate,small,Yes,Negative,252
386,23,0,Single,Student,Below Rs.10000,Post Graduate,small,Yes,Positive,276

In [30]:
data['Output'] = data['Output'].apply(lambda x: 1 if x == 'Yes' else 0)

In [32]:
data['Output'] = data['Output'].astype(float)

In [34]:
data.head(3)

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Output,Feedback,Age (Monthd)
0,20,1,Single,Student,No Income,Post Graduate,large,1.0,Positive,240
1,24,1,Single,Student,Below Rs.10000,Graduate,small,1.0,Positive,288
2,22,0,Single,Student,Below Rs.10000,Post Graduate,small,1.0,Negative,264

# Export Data

In [35]:
data.to_excel('data/cleaned_data_food_excel.xlsx', index=False)

In [36]:
data.to_csv('data/cleaned_data_food_csv.csv', index=False)

In [37]:
pd.read_excel('data/cleaned_data_food_excel.xlsx', engine='calamine')

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Output,Feedback,Age (Monthd)
0,20,1,Single,Student,No Income,Post Graduate,large,1,Positive,240
1,24,1,Single,Student,Below Rs.10000,Graduate,small,1,Positive,288
2,22,0,Single,Student,Below Rs.10000,Post Graduate,small,1,Negative,264
3,22,1,Single,Student,No Income,Graduate,large,1,Positive,264
4,22,0,Single,Student,Below Rs.10000,Post Graduate,large,1,Positive,264
...,...,...,...,...,...,...,...,...,...,...
239,21,0,Single,Student,No Income,Graduate,small,0,Positive,252
240,31,0,Married,Employee,More than 50000,Ph.D,small,1,Positive,372
241,30,0,Married,Employee,More than 50000,Post Graduate,large,1,Positive,360
242,21,0,Single,Student,No Income,Graduate,small,1,Negative,252
243,23,0,Single,Student,Below Rs.10000,Post Graduate,small,1,Positive,276

In [38]:
pd.read_csv('data/cleaned_data_food_csv.csv', engine='pyarrow')

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Output,Feedback,Age (Monthd)
0,20,1,Single,Student,No Income,Post Graduate,large,1.0,Positive,240
1,24,1,Single,Student,Below Rs.10000,Graduate,small,1.0,Positive,288
2,22,0,Single,Student,Below Rs.10000,Post Graduate,small,1.0,Negative,264
3,22,1,Single,Student,No Income,Graduate,large,1.0,Positive,264
4,22,0,Single,Student,Below Rs.10000,Post Graduate,large,1.0,Positive,264
...,...,...,...,...,...,...,...,...,...,...
239,21,0,Single,Student,No Income,Graduate,small,0.0,Positive,252
240,31,0,Married,Employee,More than 50000,Ph.D,small,1.0,Positive,372
241,30,0,Married,Employee,More than 50000,Post Graduate,large,1.0,Positive,360
242,21,0,Single,Student,No Income,Graduate,small,1.0,Negative,252
243,23,0,Single,Student,Below Rs.10000,Post Graduate,small,1.0,Positive,276