In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [4]:
data = pd.read_csv('data/credit_customers.csv', engine='pyarrow')

In [5]:
data.head(5)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,...,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad

# Deleting redundant columns

In [7]:
data.columns

Index(['checking_status', 'duration', 'credit_history', 'purpose',
       'credit_amount', 'savings_status', 'employment',
       'installment_commitment', 'personal_status', 'other_parties',
       'residence_since', 'property_magnitude', 'age', 'other_payment_plans',
       'housing', 'existing_credits', 'job', 'num_dependents', 'own_telephone',
       'foreign_worker', 'class'],
      dtype='object')

In [10]:
data.shape

(1000, 21)

In [12]:
data.drop(columns= ['checking_status', 'duration', 'credit_history', 'purpose', 'employment', 'installment_commitment', 
                    'personal_status', 'other_parties', 'residence_since', 'property_magnitude', 'other_payment_plans', 'num_dependents'], inplace=True)

In [13]:
data

,credit_amount,savings_status,age,housing,existing_credits,job,own_telephone,foreign_worker,class
0,1169.0,no known savings,67.0,own,2.0,skilled,yes,yes,good
1,5951.0,<100,22.0,own,1.0,skilled,none,yes,bad
2,2096.0,<100,49.0,own,1.0,unskilled resident,none,yes,good
3,7882.0,<100,45.0,for free,1.0,skilled,none,yes,good
4,4870.0,<100,53.0,for free,2.0,skilled,none,yes,bad
...,...,...,...,...,...,...,...,...,...
995,1736.0,<100,31.0,own,1.0,unskilled resident,none,yes,good
996,3857.0,<100,40.0,own,1.0,high qualif/self emp/mgmt,yes,yes,good
997,804.0,<100,38.0,own,1.0,skilled,none,yes,good
998,1845.0,<100,23.0,for free,1.0,skilled,yes,yes,bad
999,4576.0,100<=X<500,27.0,own,1.0,skilled,none,yes,good

In [14]:
data.drop(columns= 'savings_status', inplace=True)

In [16]:
data.head(3)

,credit_amount,age,housing,existing_credits,job,own_telephone,foreign_worker,class
0,1169.0,67.0,own,2.0,skilled,yes,yes,good
1,5951.0,22.0,own,1.0,skilled,none,yes,bad
2,2096.0,49.0,own,1.0,unskilled resident,none,yes,good

# Renaming the columns

In [19]:
data.columns

Index(['credit_amount', 'age', 'housing', 'existing_credits', 'job',
       'own_telephone', 'foreign_worker', 'class'],
      dtype='object')

In [23]:
new_columns_data_names = []

for i in data.columns:
    new_columns_data_names.append(i.capitalize())

In [24]:
new_columns_data_names

['Credit_amount',
 'Age',
 'Housing',
 'Existing_credits',
 'Job',
 'Own_telephone',
 'Foreign_worker',
 'Class']

In [25]:
data.columns = new_columns_data_names

In [26]:
data.columns

Index(['Credit_amount', 'Age', 'Housing', 'Existing_credits', 'Job',
       'Own_telephone', 'Foreign_worker', 'Class'],
      dtype='object')

# Dropping duplicates

In [27]:
data.duplicated().sum()

np.int64(0)

In [28]:
data.drop_duplicates(inplace=True)

# Remove the NaN values from dataset

In [30]:
data.isna().sum()

Credit_amount       0
Age                 0
Housing             0
Existing_credits    0
Job                 0
Own_telephone       0
Foreign_worker      0
Class               0
dtype: int64

In [32]:
data.dropna(inplace=True)

In [33]:
data

,Credit_amount,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,67.0,own,2.0,skilled,yes,yes,good
1,5951.0,22.0,own,1.0,skilled,none,yes,bad
2,2096.0,49.0,own,1.0,unskilled resident,none,yes,good
3,7882.0,45.0,for free,1.0,skilled,none,yes,good
4,4870.0,53.0,for free,2.0,skilled,none,yes,bad
...,...,...,...,...,...,...,...,...
995,1736.0,31.0,own,1.0,unskilled resident,none,yes,good
996,3857.0,40.0,own,1.0,high qualif/self emp/mgmt,yes,yes,good
997,804.0,38.0,own,1.0,skilled,none,yes,good
998,1845.0,23.0,for free,1.0,skilled,yes,yes,bad
999,4576.0,27.0,own,1.0,skilled,none,yes,good

# Check for some more Transformations

In [36]:
data['Class'].unique()

array(['good', 'bad'], dtype=object)

In [41]:
data['Class'] = data['Class'].apply(lambda x: 1 if x == 'good' else 0)
type(data['Class'][0])

numpy.int64

In [42]:
data

,Credit_amount,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,67.0,own,2.0,skilled,yes,yes,0
1,5951.0,22.0,own,1.0,skilled,none,yes,0
2,2096.0,49.0,own,1.0,unskilled resident,none,yes,0
3,7882.0,45.0,for free,1.0,skilled,none,yes,0
4,4870.0,53.0,for free,2.0,skilled,none,yes,0
...,...,...,...,...,...,...,...,...
995,1736.0,31.0,own,1.0,unskilled resident,none,yes,0
996,3857.0,40.0,own,1.0,high qualif/self emp/mgmt,yes,yes,0
997,804.0,38.0,own,1.0,skilled,none,yes,0
998,1845.0,23.0,for free,1.0,skilled,yes,yes,0
999,4576.0,27.0,own,1.0,skilled,none,yes,0

In [43]:
data['Existing_credits'][0]

np.float64(2.0)

In [45]:
data['Existing_credits'].unique()

array([2., 1., 3., 4.])

In [48]:
data['Existing_credits'] = data['Existing_credits'].astype(int)

In [50]:
data.head(3)

,Credit_amount,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,67.0,own,2,skilled,yes,yes,0
1,5951.0,22.0,own,1,skilled,none,yes,0
2,2096.0,49.0,own,1,unskilled resident,none,yes,0

# Export Data

In [51]:
data.to_excel('data/cleaned_data_credit_excel.xlsx', index=False)

In [52]:
data.to_csv('data/cleaned_data_credit_csv.csv', index=False)

In [54]:
pd.read_excel('data/cleaned_data_credit_excel.xlsx', engine='calamine').head(3)

,Credit_amount,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169,67,own,2,skilled,yes,yes,0
1,5951,22,own,1,skilled,none,yes,0
2,2096,49,own,1,unskilled resident,none,yes,0

In [55]:
pd.read_csv('data/cleaned_data_credit_csv.csv', engine='pyarrow').head(3)

,Credit_amount,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,67.0,own,2,skilled,yes,yes,0
1,5951.0,22.0,own,1,skilled,none,yes,0
2,2096.0,49.0,own,1,unskilled resident,none,yes,0