In [132]:
import pandas as pd

In [133]:
pd.__version__

'2.3.3'

# Import Data

In [134]:
data = pd.read_csv('data/hr_employee.csv')

In [135]:
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [136]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [137]:
""" 
Deleting redundant columns
Renaming the columns
Dropping duplicates
Remove the NaN values from dataset
Cleaning individual columns
Check for some more Transformations

"""

' \nDeleting redundant columns\nRenaming the columns\nDropping duplicates\nRemove the NaN values from dataset\nCleaning individual columns\nCheck for some more Transformations\n\n'

# Deleting redundant columns

In [138]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [139]:
columns_to_keep = ['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'HourlyRate', 'JobRole', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']
columns_to_drop = ['EducationField', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',  'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance']

In [140]:
len(columns_to_keep) + len(columns_to_drop)

35

In [141]:
data.shape[1]

35

In [142]:
print(data.shape[1] == len(columns_to_keep) + len(columns_to_drop))

True

## 1st Method

In [143]:
new_data = data[columns_to_keep]

In [144]:
new_data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2

## 2nd Method

In [145]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [146]:
new_data_2 = data.drop(columns=columns_to_drop)

In [147]:
new_data_2.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2

In [148]:
data.drop(columns=columns_to_drop, inplace=True)

# Renaming the columns

In [149]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'HourlyRate', 'JobRole',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [150]:
data.rename(columns= {'DistanceFromHome': 'DistanceHome'}, inplace=True)

In [151]:
data = data.rename(columns= {'DailyRate': 'DailyWage', 'HourlyRate': 'HourlyWage'})

# Dropping duplicates

In [152]:
type(data.duplicated().tail(20))

pandas.core.series.Series

In [153]:
data.duplicated().sum()

np.int64(0)

In [154]:
data.drop_duplicates(inplace=True)

In [155]:
data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [156]:
data.shape

(1470, 13)

In [157]:
data[data['YearsAtCompany'] <= 8].shape

(1022, 13)

In [158]:
data[data['Attrition'] == 'Yes']

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,50,Laboratory Technician,4,2,0,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,82,Sales Representative,5,3,0,3
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,83,Research Scientist,4,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,23,Yes,Travel_Frequently,638,Sales,9,3,33,Sales Representative,1,0,1,0
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,36,Research Scientist,2,2,2,2
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,72,Laboratory Technician,10,9,9,8
1452,50,Yes,Travel_Frequently,878,Sales,1,4,94,Sales Executive,6,3,0,1
1461,50,Yes,Travel_Rarely,410,Sales,28,3,39,Sales Executive,3,2,2,0

In [159]:
data[data['Attrition'] == 'Yes']['Attrition'].unique()

array(['Yes'], dtype=object)

In [160]:
data['Attrition'].unique()

array(['Yes', 'No'], dtype=object)

In [161]:
type(data['BusinessTravel'][1])

str

In [162]:
modify_data = data.copy()

In [163]:
modify_data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [164]:
modify_data['BusinessTravel'] = modify_data['BusinessTravel'].str.replace("_", " ")

In [165]:
modify_data['BusinessTravel'].head()

0        Travel Rarely
1    Travel Frequently
2        Travel Rarely
3    Travel Frequently
4        Travel Rarely
Name: BusinessTravel, dtype: object

In [166]:
data['BusinessTravel'] = data['BusinessTravel'].str.replace("_", " ")

# Remove the NaN values from dataset

In [167]:
data.isna()

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,False,False,False,False,False,False,False,False,False,False,False,False,False
1466,False,False,False,False,False,False,False,False,False,False,False,False,False
1467,False,False,False,False,False,False,False,False,False,False,False,False,False
1468,False,False,False,False,False,False,False,False,False,False,False,False,False
1469,False,False,False,False,False,False,False,False,False,False,False,False,False

In [168]:
data.isna().sum()

Age                        0
Attrition                  0
BusinessTravel             0
DailyWage                  0
Department                 0
DistanceHome               0
Education                  0
HourlyWage                 0
JobRole                    0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [169]:
data.dropna(inplace=True)

In [170]:
data = data.dropna()

In [171]:
data.head()

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2

# Check for some more Transformations

In [172]:
data['Attrition'] = data['Attrition'].apply(lambda x: 1 if x=='Yes' else 0)

In [173]:
data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,0,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,1,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,0,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,0,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,0,Travel Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,0,Travel Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,0,Travel Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,0,Travel Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

# Export Data

In [174]:
data.to_csv('data/cleaned_data_hr_csv.csv', index=False)

In [177]:
pd.read_csv('data/cleaned_data_hr_csv.csv', engine='pyarrow').head()

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,0,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,1,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,0,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,0,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2

In [181]:
data.to_excel('data/cleaned_data_hr_excel.xlsx', index=True)

In [182]:
pd.read_excel('data/cleaned_data_hr_excel.xlsx', engine='calamine').head()

,Unnamed: 0,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0,41,1,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,1,49,0,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,2,37,1,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,3,33,0,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,4,27,0,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2