In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
data = pd.read_csv('data/amazon_product.csv', engine='pyarrow')

In [4]:
data.head()

,,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,None,None,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,None,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,None,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,None,None,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,None,None,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,None,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,None,None,NaN

# Deleting redundant columns

In [5]:
data.columns

Index(['', 'asin', 'product_title', 'product_price', 'product_original_price',
       'currency', 'product_star_rating', 'product_num_ratings', 'product_url',
       'product_photo', 'product_num_offers', 'product_minimum_offer_price',
       'is_best_seller', 'is_amazon_choice', 'is_prime',
       'climate_pledge_friendly', 'sales_volume', 'delivery', 'has_variations',
       'product_availability', 'unit_price', 'unit_count'],
      dtype='object')

In [6]:
data.drop(columns= ['', 'asin', 'product_url', 'product_photo', 'product_num_offers', 'product_minimum_offer_price','is_amazon_choice', 'is_prime', 'climate_pledge_friendly', 'sales_volume', 'delivery', 'has_variations'], inplace=True)

In [7]:
data

,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,is_best_seller,product_availability,unit_price,unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,False,None,None,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,False,Only 7 left in stock - order soon.,None,NaN
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,None,USD,3.9,205,False,None,None,NaN
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,False,None,None,NaN
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,None,USD,4.1,423,False,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,None,USD,NaN,0,False,None,None,NaN
60,Swan Song,$14.99,$30.00,USD,4.4,14471,True,None,None,NaN
61,Bluey: Let&#x27;s Play!,$0.00,None,USD,3.5,270,False,None,None,NaN
62,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,None,USD,2.6,12,True,None,None,NaN
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,True,None,None,NaN

In [8]:
data.columns

Index(['product_title', 'product_price', 'product_original_price', 'currency',
       'product_star_rating', 'product_num_ratings', 'is_best_seller',
       'product_availability', 'unit_price', 'unit_count'],
      dtype='object')

# Renaming the columns

In [9]:
data_new_columns_names = []

for i in data.columns:
    data_new_columns_names.append(i.capitalize())

In [10]:
data.columns = data_new_columns_names

In [11]:
data.columns

Index(['Product_title', 'Product_price', 'Product_original_price', 'Currency',
       'Product_star_rating', 'Product_num_ratings', 'Is_best_seller',
       'Product_availability', 'Unit_price', 'Unit_count'],
      dtype='object')

# Dropping duplicates

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
data.drop_duplicates(inplace=True)

# Remove the NaN values from dataset

In [14]:
data.isna().sum()

Product_title              0
Product_price              0
Product_original_price    37
Currency                   0
Product_star_rating       10
Product_num_ratings        0
Is_best_seller             0
Product_availability      63
Unit_price                59
Unit_count                59
dtype: int64

In [15]:
data.isna().sum().sum()

np.int64(228)

In [16]:
data.shape

(64, 10)

In [17]:
data = data[['Product_title', 'Product_price', 'Currency', 'Product_star_rating', 'Product_num_ratings', 'Is_best_seller']]

In [18]:
data.isna().sum()

Product_title           0
Product_price           0
Currency                0
Product_star_rating    10
Product_num_ratings     0
Is_best_seller          0
dtype: int64

In [19]:
data.dropna(inplace=True)

C:\Users\Garev\AppData\Local\Temp\ipykernel_12472\1368182302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [20]:
data.isna().sum().sum()

np.int64(0)

# Check for some more Transformations

In [21]:
data.head(3)

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,False
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,4.2,135,False
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,3.9,205,False

In [22]:
data['Product_price'] = data['Product_price'].str.replace('$','')

C:\Users\Garev\AppData\Local\Temp\ipykernel_12472\1529769246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Product_price'] = data['Product_price'].str.replace('$','')

In [23]:
data['Product_price'] = data['Product_price'].astype('float')

C:\Users\Garev\AppData\Local\Temp\ipykernel_12472\4020942629.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Product_price'] = data['Product_price'].astype('float')

In [33]:
data['Product_price'] = data['Product_price'].apply(lambda x: round(x))

C:\Users\Garev\AppData\Local\Temp\ipykernel_12472\2924814354.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Product_price'] = data['Product_price'].apply(lambda x: round(x))

In [34]:
data.head(3)

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,100,USD,4.0,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",150,USD,4.2,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,50,USD,3.9,205,0

In [25]:
data.dtypes

Product_title           object
Product_price          float64
Currency                object
Product_star_rating    float64
Product_num_ratings      int64
Is_best_seller            bool
dtype: object

In [26]:
data.dtypes

Product_title           object
Product_price          float64
Currency                object
Product_star_rating    float64
Product_num_ratings      int64
Is_best_seller            bool
dtype: object

In [27]:
data.head()

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,USD,4.0,2929,False
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,USD,4.2,135,False
2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,USD,3.9,205,False
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,USD,4.3,2248,False
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,USD,4.1,423,False

In [28]:
data['Is_best_seller'].unique()

array([False,  True])

In [29]:
data['Is_best_seller'] = data['Is_best_seller'].apply(lambda x: 1 if x==True else 0)

C:\Users\Garev\AppData\Local\Temp\ipykernel_12472\2965320206.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Is_best_seller'] = data['Is_best_seller'].apply(lambda x: 1 if x==True else 0)

In [30]:
data['Is_best_seller'].unique()

array([0, 1])

In [31]:
data.head(15)

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,USD,4.0,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,USD,4.2,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,USD,3.9,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,USD,4.3,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,USD,4.1,423,0
5,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",129.99,USD,4.2,578,0
6,"SAMSUNG Galaxy A35 5G A Series Cell Phone, 128...",349.99,USD,4.4,109,0
7,TracFone | Motorola Moto g Pure | Locked | 32G...,49.39,USD,4.2,2771,0
8,"SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32G...",87.10,USD,3.9,613,0
9,Moto G Play | 2024 | Unlocked | Made for US 4/...,129.99,USD,4.1,94,0
10,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",70.61,USD,3.9,462,0
11,AT&amp;T BL102-2 DECT 6.0 2-Handset Cordless P...,48.75,USD,4.3,26685,1
12,Bold K10 | 2024 | 3-Day Battery | Unlocked | 6...,99.99,USD,3.8,8,0
13,Google Pixel 8 - Unlocked Android Smartphone w...,499.00,USD,4.3,2098,0
14,Motorola Moto G Power 5G | 2023 | Unlocked | M...,199.99,USD,4.2,2258,0

# Import Data

In [35]:
data.to_excel('data/cleaned_data_amazon_excel.xlsx')

In [41]:
pd.read_excel('data/cleaned_data_amazon_excel.xlsx', engine='calamine').head()

,Unnamed: 0,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,0,Moto G Play 2023 3-Day Battery Unlocked Made f...,100,USD,4.0,2929,0
1,1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",150,USD,4.2,135,0
2,2,Total by Verizon | Samsung Galaxy A03s | Locke...,50,USD,3.9,205,0
3,3,Google Pixel 7a - Unlocked Android Cell Phone ...,335,USD,4.3,2248,0
4,4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",200,USD,4.1,423,0

In [38]:
data.to_csv('data/cleaned_data_amazon_csv.csv')

In [40]:
pd.read_csv('data/cleaned_data_amazon_csv.csv', engine='pyarrow').head(5)

,,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,0,Moto G Play 2023 3-Day Battery Unlocked Made f...,100,USD,4.0,2929,0
1,1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",150,USD,4.2,135,0
2,2,Total by Verizon | Samsung Galaxy A03s | Locke...,50,USD,3.9,205,0
3,3,Google Pixel 7a - Unlocked Android Cell Phone ...,335,USD,4.3,2248,0
4,4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",200,USD,4.1,423,0